---
fabric_name: DC1_FABRIC

underlay_routing_protocol: EBGP

overlay_routing_protocol: EBGP

underlay_p2p_network_summary: 172.31.255.0/24

overlay_loopback_network_summary: 192.168.255.0/24

vtep_loopback_network_summary: 192.168.254.0/24

vtep_vvtep_ip: 192.168.254.254/32

mlag_ips:
  leaf_peer_l3: 10.255.251.0/24
  mlag_peer: 10.255.252.0/24

vxlan_vlan_aware_bundles: false

# bgp peer groups passwords
bgp_peer_groups:
  IPv4_UNDERLAY_PEERS:
    password: "AQQvKeimxJu+uGQ/yYvv9w=="
  EVPN_OVERLAY_PEERS:
      password: "q+VNViP5i4rVjW1cxFv2wA=="
  MLAG_IPv4_UNDERLAY_PEER:
      password: "vnEaG8gMeQf3d3cN6PktXQ=="

spine:
  platform: cEOS-LAB
  bgp_as: 65001
  leaf_as_range: 65101-65132
  nodes:
    DC1_SPINE1:
      id: 1
      mgmt_ip: 172.100.100.2/24
    DC1_SPINE2:
      id: 2
      mgmt_ip: 172.100.100.3/24

l3leaf:
  defaults:
    platform: cEOS-LAB
    bgp_as: 65100
    spines: [DC1_SPINE1, DC1_SPINE2]
    uplink_to_spine_interfaces: [Ethernet1, Ethernet2]
    spanning_tree_mode: mstp
    spanning_tree_priority: 4096
    evpn_services_l2_only: true
  node_groups:
    DC1_LEAF1:
      bgp_as: 65101
      mlag_interfaces: [Ethernet3, Ethernet4]
      nodes:
        DC1_LEAF1A:
          id: 1
          mgmt_ip: 172.100.100.4/24
          spine_interfaces: [Ethernet1, Ethernet1]
        DC1_LEAF1B:
          id: 2
          mgmt_ip: 172.100.100.5/24
          spine_interfaces: [Ethernet2, Ethernet2]
    DC1_LEAF2:
      bgp_as: 65102
      nodes:
        DC1_LEAF2A:
          id: 3
          mgmt_ip: 172.100.100.6/24
          spine_interfaces: [Ethernet3, Ethernet3]
    DC1_SVC1:
      bgp_as: 65103
      mlag_interfaces: [Ethernet3, Ethernet4]
      evpn_services_l2_only: false
      virtual_router_mac_address: 00:00:00:00:00:01       
      nodes:
        DC1_SVC1A:
          id: 4
          mgmt_ip: 172.100.100.7/24
          spine_interfaces: [Ethernet4, Ethernet4]
        DC1_SVC1B:
          id: 5
          mgmt_ip: 172.100.100.8/24
          spine_interfaces: [Ethernet5, Ethernet5]

# Spine BGP Tuning | Optional.
spine_bgp_defaults:
  #- update wait-for-convergence
  #- update wait-install
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200
  #- graceful-restart restart-time 300
  #- graceful-restart

# Leaf BGP Tuning | Optional.
leaf_bgp_defaults:
  #- update wait-install
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200
  #- graceful-restart restart-time 300
  #- graceful-restart