---
fabric_name: DC1_FABRIC

underlay_routing_protocol: OSPF

overlay_routing_protocol: IBGP

vxlan_vlan_aware_bundles: true

underlay_ospf_process_id: 100
underlay_ospf_area: 0.0.0.0
underlay_ospf_max_lsa: 12000
underlay_ospf_bfd_enable: true

bgp_as: 65001

bgp_peer_groups:
  EVPN_OVERLAY_PEERS:
      password: "q+VNViP5i4rVjW1cxFv2wA=="

spine:
  defaults:
    platform: cEOS-LAB
    loopback_ipv4_pool: 192.168.255.0/24
    bgp_defaults:
      #- update wait-for-convergence
      #- update wait-install
      - no bgp default ipv4-unicast
      - distance bgp 20 200 200
      #- graceful-restart restart-time 300
      #- graceful-restart
  nodes:
    DC1_SPINE1:
      id: 1
      mgmt_ip: 172.100.100.2/24
    DC1_SPINE2:
      id: 2
      mgmt_ip: 172.100.100.3/24

l3leaf:
  defaults:
    platform: cEOS-LAB
    uplink_switches: [DC1_SPINE1, DC1_SPINE2]
    uplink_interfaces: [Ethernet1, Ethernet2]
    mlag_interfaces: [Ethernet3, Ethernet4]
    virtual_router_mac_address: 00:00:00:00:00:01
    spanning_tree_mode: mstp
    spanning_tree_priority: 4096
    loopback_ipv4_pool: 192.168.255.0/24
    loopback_ipv4_offset: 2
    vtep_loopback_ipv4_pool: 192.168.254.0/24
    uplink_ipv4_pool: 172.31.255.0/24
    mlag_peer_ipv4_pool: 10.255.252.0/24
    mlag_peer_l3_ipv4_pool: 10.255.251.0/24
    bgp_defaults:
      #- update wait-install
      - no bgp default ipv4-unicast
      - distance bgp 20 200 200
      #- graceful-restart restart-time 300
      #- graceful-restart
  node_groups:
    DC1_LEAF1:
      filter:
        tenants: [ Tenant_A ]
        tags: [ opzone_pod1 ]
      nodes:
        DC1_LEAF1A:
          id: 1
          mgmt_ip: 172.100.100.4/24
          uplink_switch_interfaces: [Ethernet1, Ethernet1]
        DC1_LEAF1B:
          id: 2
          mgmt_ip: 172.100.100.5/24
          uplink_switch_interfaces: [Ethernet2, Ethernet2]
    DC1_LEAF2:
      filter:
        tenants: [ Tenant_A ]
        tags: [ opzone_pod2 ]
      nodes:
        DC1_LEAF2A:
          id: 3
          mgmt_ip: 172.100.100.6/24
          uplink_switch_interfaces: [Ethernet3, Ethernet3]
        DC1_LEAF2B:
          id: 4
          mgmt_ip: 172.100.100.7/24
          uplink_switch_interfaces: [Ethernet4, Ethernet4]

